name: 'minio::mc'

on:
    schedule:
        - cron: '0 16 * * *'
    workflow_dispatch:

    jobs:
        ci:
        if: github.repository == 'Loongson-Cloud-Community/container-ci'
        runs-on: self-hosted
        steps:
            - name: Checkout Code
              uses: actions/checkout@v3

            - name: Run ci.sh
              run: |
                date
                pushd minio/mc && ./ci.sh && pop

